display encounter attempt success

diff --git a/gw2-dpsreport/bin b/gw2-dpsreport/bin
--- a/gw2-dpsreport/bin
+++ b/gw2-dpsreport/bin
@@ -169,7 +169,9 @@ compress_log () {
     fi
 }
 
-# upload log file at the given path, and print the URL if it succeeded
+# upload log file at the given path
+# write line: RESULT URL
+# RESULT: adjective describing whether the encounter attempt succeeded
 upload_log () {
     local orig_file="$1"
     local tmp_file
@@ -196,28 +198,43 @@ upload_log () {
     [ "$err_code" -ne 0 ] && return 1
 
     local err
-    err="$(jshon -e error <<<"$res")"
+    err="$(jshon -Q -e error <<<"$res")"
     if [ "$?" != 0 ] || [ "$err" != null ]; then
         echo >&2 "error: $file: ${err:-unknown}"
         return 1
     fi
 
+    local result=unknown
+    local success
+    if success="$(jshon -Q -e encounter -e success <<<"$res")"; then
+        if [ "$success" = true ]; then
+            result=success
+        elif [ "$success" = false ]; then
+            result=failure
+        fi
+    fi
+
     local link
-    link="$(jshon -e permalink -u <<<"$res")" || {
+    link="$(jshon -Q -e permalink -u <<<"$res")" || {
         echo >&2 "error: $file: unexpected HTTP response: $res"
         return 1
     }
-    echo "$link"
+
+    echo "$result $link"
 }
 
 # upload log files; failed uploads are also printed, but without the upload URL
 # read lines: NUM_BOSS_ATTEMPTS FILE_PATH
-# write lines: NUM_BOSS_ATTEMPTS/BOSS_NAME/[URL]
+# write lines: NUM_BOSS_ATTEMPTS/BOSS_NAME/RESULT/[URL]
 upload_logs () {
     local num_attempts
     local f
     while read -r num_attempts f; do
-        echo "$num_attempts/$(parse_path_boss_name "$f")/$(upload_log "$f")"
+        local result
+        local url
+        read -r result url < <(upload_log "$f")
+        [ -z "$result" ] && result=unknown
+        echo "$num_attempts/$(parse_path_boss_name "$f")/$result/$url"
     done
 }
 
@@ -233,14 +250,16 @@ buffer_input () {
 }
 
 # print log upload results in a human-readable format
-# read lines: NUM_BOSS_ATTEMPTS/BOSS_NAME/[URL]
+# read lines: NUM_BOSS_ATTEMPTS/BOSS_NAME/RESULT/[URL]
 display_results () {
     local line
     while read -r line; do
         local num_attempts="${line%%/*}"; line="${line#*/}"
-        local boss_name="${line%%/*}"
+        local boss_name="${line%%/*}"; line="${line#*/}"
+        local result="${line%%/*}"
         local url="${line#*/}"
-        echo "$boss_name (attempts: $num_attempts): ${url:-[upload failed]}"
+        echo -n "$boss_name (attempts: $num_attempts, $result): "
+        echo "${url:-[upload failed]}"
     done
 }
 
