gw2-dpsreport: compress before upload

diff --git a/gw2-dpsreport/bin b/gw2-dpsreport/bin
--- a/gw2-dpsreport/bin
+++ b/gw2-dpsreport/bin
@@ -11,6 +11,7 @@ DAY_START_TIME=05:00:00
 # min bytes for file to be counted as an attempt (2MB/300kB)
 ATTEMPTS_THRESHOLD_RAW=2000000
 ATTEMPTS_THRESHOLD_ZIP=300000
+TEMP_DIR="$(mktemp -d)"
 
 DAY="$1"
 
@@ -31,6 +32,10 @@ date &> /dev/null --date="$DAY" "+%Y%m%d %H:%M:%S" || {
     echo >&2 "error: invalid day: $DAY"
     exit 2
 }
+type -p zip > /dev/null || {
+    echo >&2 -n "warning: zip not found; "
+    echo >&2 "uncompressed logs will be uploaded without compression"
+}
 
 # given log file path, print boss name
 parse_path_boss_name () {
@@ -44,6 +49,11 @@ parse_path_date () {
     local date="$(basename "$f")"
     date="${date/-/}"
     echo "${date%.*}"
+}
+
+# remove all created temporary files
+cleanup () {
+    rm -rf "$TEMP_DIR"
 }
 
 # filter log files to those that were recorded on the day specified in $DAY
@@ -140,14 +150,42 @@ filter_logs_grouped () {
         done
 }
 
+# compress_log LOG_FILE TMP_FILE
+#
+# compress LOG_FILE, if necessary, and write the result to TMP_FILE
+# prints the new file path, which might be LOG_FILE or TMP_FILE
+compress_log () {
+    local file="$1"
+    local tmp_file="$2"
+    local ext="${file##*.}"
+
+    if type -p zip > /dev/null &&
+        [ "$ext" = evtc ] &&
+        zip -q - -- "$file" > "$tmp_file"
+    then
+        echo "$tmp_file"
+    else
+        echo "$file"
+    fi
+}
+
 # upload log file at the given path, and print the URL if it succeeded
 upload_log () {
     local file="$1"
+    local tmp_file
+    # curl uses filename as multipart filename by default, and the server uses
+    # the extension to determine file type
+    tmp_file="$(mktemp -p "$TEMP_DIR" -q --suffix=.zip)" &&
+        file="$(compress_log "$file" "$tmp_file")"
+
     local url="$URL"/uploadContent
     local res
     res="$(
         curl --progress-bar "$url" -F file=@"$file" -F json=1
-    )" || return 1
+    )"
+    local err_code="$?"
+    [ -n "$tmp_file" ] && rm -f "$tmp_file"
+    [ "$err_code" -ne 0 ] && return 1
 
     local err
     err="$(jshon -e error <<<"$res")"
@@ -198,6 +236,7 @@ display_results () {
     done
 }
 
+trap cleanup TERM INT EXIT
 for f in "$LOGS_PATH"/*/*.evtc{,.zip}; do echo "$f"; done |
     filter_logs_time |
     filter_logs_size |
