gw2-arcdps-install: take dir from environment

diff --git a/gw2-arcdps-install/bin b/gw2-arcdps-install/bin
--- a/gw2-arcdps-install/bin
+++ b/gw2-arcdps-install/bin
@@ -1,34 +1,40 @@
 #! /usr/bin/env bash
 
-base_url="http://www.deltaconnected.com/arcdps/x64/"
-dll_name="d3d9.dll"
-bt_dll_name="d3d9_arcdps_buildtemplates.dll"
+BASE_URL="http://www.deltaconnected.com/arcdps/x64/"
+DLL_NAME="d3d9.dll"
+BT_DLL_NAME="d3d9_arcdps_buildtemplates.dll"
 
-install_dir="$1"
-[ -z "$install_dir" ] && {
-    echo >&2 "expected first argument: Guild Wars 2 installation directory"
+INSTALL_PATH="$GW2_INSTALL_PATH"
+
+[ -z "$INSTALL_PATH" ] && {
+    if [ -n "$WINEPREFIX" ]; then
+        INSTALL_PATH="$WINEPREFIX/drive_c/Program Files/Guild Wars 2"
+    else
+        echo >&2 "error: environment variable not set: GW2_INSTALL_PATH"
+        exit 2
+    fi
+}
+[ -d "$INSTALL_PATH" ] || {
+    echo >&2 "error: not a directory: $INSTALL_PATH"
     exit 2
 }
-[ -d "$install_dir" ] || {
-    echo >&2 "no such directory: $install_dir"
+INSTALL_PATH="$INSTALL_PATH/bin64"
+[ -d "$INSTALL_PATH" ] || {
+    echo >&2 "no such directory: $INSTALL_PATH"
     exit 2
 }
-install_dir="$install_dir/bin64"
-[ -d "$install_dir" ] || {
-    echo >&2 "no such directory: $install_dir"
-    exit 2
-}
+echo >&2 "info: installing to directory: $INSTALL_PATH"
 
 tmp="$(mktemp -d)"
 cd "$tmp"
 
 wget --no-verbose \
-    "$base_url/$dll_name" "$base_url/$dll_name.md5sum" \
-    "$base_url/buildtemplates/$bt_dll_name" || exit 1
+    "$BASE_URL/$DLL_NAME" "$BASE_URL/$DLL_NAME.md5sum" \
+    "$BASE_URL/buildtemplates/$BT_DLL_NAME" || exit 1
 # md5sum file expects files to be in directory `x64`
 mkdir x64 || exit 1
-cp "$dll_name" "$bt_dll_name" x64 || exit 1
-md5sum --quiet --check "$dll_name.md5sum" || exit 1
-install -m644 "$dll_name" "$bt_dll_name" "$install_dir" || exit 1
+cp "$DLL_NAME" "$BT_DLL_NAME" x64 || exit 1
+md5sum --quiet --check "$DLL_NAME.md5sum" || exit 1
+install -m644 "$DLL_NAME" "$BT_DLL_NAME" "$INSTALL_PATH" || exit 1
 
 rm -rf "$tmp"
